-- MySQL Script generated by MySQL Workbench
-- Wed Dec  3 10:07:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLLEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLLEN` (
  `rol_id` INT NOT NULL,
  `rol_naam` VARCHAR(45) NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GEBRUIKERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GEBRUIKERS` (
  `gebruiker_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  `ROLLEN_rol_id` INT NOT NULL,
  PRIMARY KEY (`gebruiker_id`),
  INDEX `fk_GEBRUIKERS_ROLLEN_idx` (`ROLLEN_rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_GEBRUIKERS_ROLLEN`
    FOREIGN KEY (`ROLLEN_rol_id`)
    REFERENCES `mydb`.`ROLLEN` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVERINGEN BANEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESERVERINGEN BANEN` (
  `reservering_baan_id` INT NOT NULL,
  PRIMARY KEY (`reservering_baan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVERINGEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESERVERINGEN` (
  `reservering_id` INT NOT NULL,
  `datum` DATE NULL,
  `start_tijd` TIME NULL,
  `eind_tijd` TIME NULL,
  `kinderhekjes` TINYINT NULL,
  `GEBRUIKERS_gebruiker_id` INT NOT NULL,
  `RESERVERINGEN BANEN_reservering_baan_id` INT NOT NULL,
  PRIMARY KEY (`reservering_id`),
  INDEX `fk_RESERVERINGEN_GEBRUIKERS1_idx` (`GEBRUIKERS_gebruiker_id` ASC) VISIBLE,
  INDEX `fk_RESERVERINGEN_RESERVERINGEN BANEN1_idx` (`RESERVERINGEN BANEN_reservering_baan_id` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVERINGEN_GEBRUIKERS1`
    FOREIGN KEY (`GEBRUIKERS_gebruiker_id`)
    REFERENCES `mydb`.`GEBRUIKERS` (`gebruiker_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVERINGEN_RESERVERINGEN BANEN1`
    FOREIGN KEY (`RESERVERINGEN BANEN_reservering_baan_id`)
    REFERENCES `mydb`.`RESERVERINGEN BANEN` (`reservering_baan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANEN` (
  `baan_id` INT NOT NULL,
  `baan_nummer` INT NULL,
  `RESERVERINGEN_reservering_id` INT NOT NULL,
  PRIMARY KEY (`baan_id`),
  INDEX `fk_BANEN_RESERVERINGEN1_idx` (`RESERVERINGEN_reservering_id` ASC) VISIBLE,
  CONSTRAINT `fk_BANEN_RESERVERINGEN1`
    FOREIGN KEY (`RESERVERINGEN_reservering_id`)
    REFERENCES `mydb`.`RESERVERINGEN` (`reservering_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
